### ISSUE TITLE
Request body is not passed to the next request when status code is 300 Multiple Choices

### ISSUE THREAD

**Issue by rvichery** [nuagenetworks/go-bambou#10]
When VSD sends back a status code equals to 300 Multiple Choices, the body of the original request is not passed to the next request (with responseChoice=1 appended).

The issue comes from this line https://github.com/nuagenetworks/go-bambou/blob/e56bbad500a86dec68d009d7ed3dfa71f1038c34/bambou/session.go#L234 where the body is passed using request.Body (and not by using `request.GetBody` function). In the net/http library, the `Body` attribute within the `Request` structure only gets a non empty value only if the `newRequest` function is provided with an `io.ReadCloser ` as the `Body` parameter. In our case we use a `bytes.Buffer`. 

A better way of handling this would have been to modify the value of the `URL` attribute within the original `Request` object.

**Comment by pdellaert** [comment]
Ah, the `GetBody` explains the issue, thanks :)
